spring:
  application:
    name: Logistics-Management
  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: logistics_db
    schema-action: create_if_not_exists
  thymeleaf:
      cache: false
server:
    port: 8080