spring:
  application:
    name: Logistics-Management

  cassandra:
    contact-points: 172.30.37.96
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: logistics_db
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra

  thymeleaf:
    cache: false

server:
  port: 8080
