spring:
  application:
    name: Logistics-Management

  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    session-keyspace: logistics_db
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra
  thymeleaf:
    cache: false

server:
  port: 8080
